"""Added continent and region fields to Country model

Revision ID: 09946565e10a
Revises: 2c10bbf2c6a8
Create Date: 2026-02-28 18:57:37.596750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09946565e10a'
down_revision: Union[str, None] = '2c10bbf2c6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_importance_rank', table_name='feature_importance')
    op.drop_index('idx_importance_version', table_name='feature_importance')
    op.drop_index('idx_data_country_year', table_name='indicator_data')
    op.drop_index('idx_data_extrapolated', table_name='indicator_data')
    op.drop_index('idx_data_indicator_year', table_name='indicator_data')
    op.drop_index('indicator_data_year_idx', table_name='indicator_data')
    op.drop_index('idx_indicators_category', table_name='indicators')
    op.drop_index('idx_indicators_code', table_name='indicators')
    op.drop_index('idx_predictions_country_year_scenario', table_name='model_predictions')
    op.drop_index('idx_predictions_median', table_name='model_predictions')
    op.drop_index('idx_predictions_p10', table_name='model_predictions')
    op.drop_index('idx_predictions_p90', table_name='model_predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_predictions_p90', 'model_predictions', ['predicted_gdp_p90'], unique=False)
    op.create_index('idx_predictions_p10', 'model_predictions', ['predicted_gdp_p10'], unique=False)
    op.create_index('idx_predictions_median', 'model_predictions', ['predicted_gdp_median'], unique=False)
    op.create_index('idx_predictions_country_year_scenario', 'model_predictions', ['country_code', 'year', 'scenario'], unique=False)
    op.create_index('idx_indicators_code', 'indicators', ['indicator_code'], unique=False)
    op.create_index('idx_indicators_category', 'indicators', ['category'], unique=False)
    op.create_index('indicator_data_year_idx', 'indicator_data', [sa.text('year DESC')], unique=False)
    op.create_index('idx_data_indicator_year', 'indicator_data', ['indicator_id', 'year'], unique=False)
    op.create_index('idx_data_extrapolated', 'indicator_data', ['is_extrapolated'], unique=False)
    op.create_index('idx_data_country_year', 'indicator_data', ['country_code', 'year'], unique=False)
    op.create_index('idx_importance_version', 'feature_importance', ['model_version_id'], unique=False)
    op.create_index('idx_importance_rank', 'feature_importance', ['rank'], unique=False)
    # ### end Alembic commands ###
