"""Initial schema - countries, indicators, predictions

Revision ID: 2c10bbf2c6a8
Revises: 
Create Date: 2026-02-28 18:03:12.785349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c10bbf2c6a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
    sa.Column('indicator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('indicator_name', sa.String(length=200), nullable=False),
    sa.Column('simplified_name', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('indicator_id'),
    sa.UniqueConstraint('indicator_code')
    )
    op.create_table('model_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version_name', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_list', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('training_start_year', sa.Integer(), nullable=True),
    sa.Column('training_end_year', sa.Integer(), nullable=True),
    sa.Column('holdout_start_year', sa.Integer(), nullable=True),
    sa.Column('holdout_end_year', sa.Integer(), nullable=True),
    sa.Column('cv_r2', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('cv_rmse', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('holdout_r2', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('holdout_rmse', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('holdout_mape', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('deployed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('version_id'),
    sa.UniqueConstraint('version_name')
    )
    op.create_table('feature_importance',
    sa.Column('importance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('importance_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('catboost_importance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('xgboost_importance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('ensemble_importance', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.indicator_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('importance_id'),
    sa.UniqueConstraint('model_version_id', 'indicator_id', name='uq_feature_importance')
    )
    op.create_table('indicator_data',
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('is_extrapolated', sa.Boolean(), nullable=True),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.indicator_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('country_code', 'indicator_id', 'year')
    )
    op.create_table('model_predictions',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(length=20), nullable=True),
    sa.Column('predicted_gdp_median', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('predicted_gdp_p10', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('predicted_gdp_p90', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bootstrap_mean', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bootstrap_std', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bootstrap_ci95_lower', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bootstrap_ci95_upper', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('dampening_factor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['country_code'], ['countries.country_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id'),
    sa.UniqueConstraint('country_code', 'year', 'scenario', 'model_version', name='uq_prediction')
    )
    op.add_column('countries', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('countries', 'updated_at')
    op.drop_table('model_predictions')
    op.drop_table('indicator_data')
    op.drop_table('feature_importance')
    op.drop_table('model_versions')
    op.drop_table('indicators')
    # ### end Alembic commands ###
