"""Add continent field and define indexes in models

Revision ID: 48782dd66fec
Revises: 09946565e10a
Create Date: 2026-02-28 19:09:46.170502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48782dd66fec'
down_revision: Union[str, None] = '09946565e10a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('continent', sa.String(length=50), nullable=True))
    op.create_index('idx_importance_rank', 'feature_importance', ['rank'], unique=False)
    op.create_index('idx_importance_version', 'feature_importance', ['model_version_id'], unique=False)
    op.create_index('idx_data_country_year', 'indicator_data', ['country_code', 'year'], unique=False)
    op.create_index('idx_data_extrapolated', 'indicator_data', ['is_extrapolated'], unique=False)
    op.create_index('idx_data_indicator_year', 'indicator_data', ['indicator_id', 'year'], unique=False)
    op.create_index('idx_indicators_category', 'indicators', ['category'], unique=False)
    op.create_index('idx_indicators_code', 'indicators', ['indicator_code'], unique=False)
    op.create_index('idx_predictions_country_year_scenario', 'model_predictions', ['country_code', 'year', 'scenario'], unique=False)
    op.create_index('idx_predictions_median', 'model_predictions', ['predicted_gdp_median'], unique=False)
    op.create_index('idx_predictions_p10', 'model_predictions', ['predicted_gdp_p10'], unique=False)
    op.create_index('idx_predictions_p90', 'model_predictions', ['predicted_gdp_p90'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_predictions_p90', table_name='model_predictions')
    op.drop_index('idx_predictions_p10', table_name='model_predictions')
    op.drop_index('idx_predictions_median', table_name='model_predictions')
    op.drop_index('idx_predictions_country_year_scenario', table_name='model_predictions')
    op.drop_index('idx_indicators_code', table_name='indicators')
    op.drop_index('idx_indicators_category', table_name='indicators')
    op.drop_index('idx_data_indicator_year', table_name='indicator_data')
    op.drop_index('idx_data_extrapolated', table_name='indicator_data')
    op.drop_index('idx_data_country_year', table_name='indicator_data')
    op.drop_index('idx_importance_version', table_name='feature_importance')
    op.drop_index('idx_importance_rank', table_name='feature_importance')
    op.drop_column('countries', 'continent')
    # ### end Alembic commands ###
