"""Added economy_type field, removed quantile and bootstrapping fields and added new fields in ModelPrediction (predicted_gdp_per_capita, ci_80_lower, ci_80_upper, and is_baseline

Revision ID: 908bb7404fd3
Revises: 11d0db73f5e0
Create Date: 2026-03-15 16:47:53.039830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908bb7404fd3'
down_revision: Union[str, None] = '11d0db73f5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
