"""Added economy_type field, removed quantile and bootstrapping fields and added new fields in ModelPrediction (predicted_gdp_per_capita, ci_80_lower, ci_80_upper, and is_baseline

Revision ID: d944d7a367c6
Revises: 908bb7404fd3
Create Date: 2026-03-15 16:55:22.376002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd944d7a367c6'
down_revision: Union[str, None] = '908bb7404fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('economy_type', sa.String(length=20), nullable=True))
    op.add_column('model_predictions', sa.Column('predicted_gdp_per_capita', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('model_predictions', sa.Column('ci_80_lower', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('model_predictions', sa.Column('ci_80_upper', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('model_predictions', sa.Column('is_baseline', sa.Boolean(), nullable=True))
    op.drop_index('idx_predictions_country_year_scenario', table_name='model_predictions')
    op.drop_index('idx_predictions_median', table_name='model_predictions')
    op.drop_index('idx_predictions_p10', table_name='model_predictions')
    op.drop_index('idx_predictions_p90', table_name='model_predictions')
    op.drop_constraint('uq_prediction', 'model_predictions', type_='unique')
    op.create_unique_constraint('uq_prediction', 'model_predictions', ['country_code', 'year', 'model_version'])
    op.create_index('idx_predictions_country_year', 'model_predictions', ['country_code', 'year'], unique=False)
    op.create_index('idx_predictions_is_baseline', 'model_predictions', ['is_baseline'], unique=False)
    op.create_index('idx_predictions_model_version', 'model_predictions', ['model_version'], unique=False)
    op.drop_column('model_predictions', 'predicted_gdp_median')
    op.drop_column('model_predictions', 'predicted_gdp_p10')
    op.drop_column('model_predictions', 'dampening_factor')
    op.drop_column('model_predictions', 'bootstrap_std')
    op.drop_column('model_predictions', 'bootstrap_ci95_upper')
    op.drop_column('model_predictions', 'scenario')
    op.drop_column('model_predictions', 'bootstrap_mean')
    op.drop_column('model_predictions', 'predicted_gdp_p90')
    op.drop_column('model_predictions', 'bootstrap_ci95_lower')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_predictions', sa.Column('bootstrap_ci95_lower', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('predicted_gdp_p90', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('bootstrap_mean', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('scenario', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('bootstrap_ci95_upper', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('bootstrap_std', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('dampening_factor', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('predicted_gdp_p10', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('model_predictions', sa.Column('predicted_gdp_median', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.drop_index('idx_predictions_model_version', table_name='model_predictions')
    op.drop_index('idx_predictions_is_baseline', table_name='model_predictions')
    op.drop_index('idx_predictions_country_year', table_name='model_predictions')
    op.drop_constraint('uq_prediction', 'model_predictions', type_='unique')
    op.create_unique_constraint('uq_prediction', 'model_predictions', ['country_code', 'year', 'scenario', 'model_version'])
    op.create_index('idx_predictions_p90', 'model_predictions', ['predicted_gdp_p90'], unique=False)
    op.create_index('idx_predictions_p10', 'model_predictions', ['predicted_gdp_p10'], unique=False)
    op.create_index('idx_predictions_median', 'model_predictions', ['predicted_gdp_median'], unique=False)
    op.create_index('idx_predictions_country_year_scenario', 'model_predictions', ['country_code', 'year', 'scenario'], unique=False)
    op.drop_column('model_predictions', 'is_baseline')
    op.drop_column('model_predictions', 'ci_80_upper')
    op.drop_column('model_predictions', 'ci_80_lower')
    op.drop_column('model_predictions', 'predicted_gdp_per_capita')
    op.drop_column('countries', 'economy_type')
    # ### end Alembic commands ###
